---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
  namespace: health-app
  labels:
    app: patient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: us-central1-docker.pkg.dev/cloudcomputing-cw-bda/cloud-computing/patient-health-record:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-uri-secret-patient
                  key: MONGODB_URI